import { NextResponse } from 'next/server';
import { Octokit } from '@octokit/rest';
import { createGroq } from '@ai-sdk/groq';
import { generateText } from 'ai';

const groq = createGroq({
  apiKey: process.env.GROQ_API_KEY,
});

async function summariseReadme(readme: string): Promise<string> {
  try {
    const { text } = await generateText({
      model: groq('llama3-8b-8192'),
      prompt: `Summarise this README in 3-4 sentences, focusing on what the project does, tech stack, and key features:\n\n${readme.slice(0, 3000)}`,
    });
    return text;
  } catch {
    return readme.slice(0, 500); // fallback if summarisation fails
  }
}

const CODE_EXTENSIONS = new Set([
  'js', 'jsx', 'ts', 'tsx', 'py', 'java', 'c', 'cc', 'cpp', 'h', 'hpp',
  'cs', 'go', 'rs', 'kt', 'swift', 'php', 'rb', 'scala', 'sh', 'sql',
]);

const IGNORE_PATH_PARTS = [
  'node_modules/',
  'dist/',
  'build/',
  '.next/',
  '.git/',
  'vendor/',
  'coverage/',
  'target/',
  'out/',
  'bin/',
  'obj/',
];

const COMMON_BOILERPLATE_TOKENS = [
  'generated by',
  'next.config',
  'tailwind',
  'react.strictmode',
  'export default function',
  'createRoot',
  'from "react"',
  'from \"react\"',
  'import react',
  'use client',
];

type RepoFile = {
  path: string;
  sha: string;
  size: number;
};

type PlagiarismEvidence = {
  snippet: string;
  matches: number;
  uniqueRepos: string[];
};

function isCodeFile(path: string): boolean {
  const lower = path.toLowerCase();
  if (IGNORE_PATH_PARTS.some(part => lower.includes(part))) return false;
  const ext = lower.split('.').pop();
  return !!ext && CODE_EXTENSIONS.has(ext);
}

function normalizeCode(content: string): string {
  return content
    .replace(/\/\*[\s\S]*?\*\//g, ' ')
    .replace(/(^|\s+)\/\/.*$/gm, ' ')
    .replace(/(^|\s+)#.*$/gm, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .toLowerCase();
}

function isLowSignalSnippet(snippet: string): boolean {
  const lower = snippet.toLowerCase();
  return COMMON_BOILERPLATE_TOKENS.some(token => lower.includes(token));
}

function extractSnippets(normalizedFiles: string[]): string[] {
  const snippets: string[] = [];

  for (const content of normalizedFiles) {
    if (content.length < 240) continue;

    const windowSize = 180;
    const startPositions = [
      Math.floor(content.length * 0.2),
      Math.floor(content.length * 0.5),
      Math.floor(content.length * 0.75),
    ];

    for (const pos of startPositions) {
      const start = Math.max(0, Math.min(pos, content.length - windowSize));
      const snippet = content.slice(start, start + windowSize).trim();

      if (snippet.length < 120 || isLowSignalSnippet(snippet)) continue;
      if (snippets.some(existing => existing.includes(snippet) || snippet.includes(existing))) continue;

      snippets.push(snippet);
      if (snippets.length >= 3) return snippets;
    }
  }

  return snippets;
}

async function fetchFileContent(
  octokit: Octokit,
  owner: string,
  repo: string,
  fileSha: string,
): Promise<string | null> {
  try {
    const blob = await octokit.git.getBlob({ owner, repo, file_sha: fileSha });
    return Buffer.from(blob.data.content, 'base64').toString('utf-8');
  } catch {
    return null;
  }
}

async function detectPlagiarism(
  octokit: Octokit,
  owner: string,
  repo: string,
  files: RepoFile[],
): Promise<{ score: number; evidence: PlagiarismEvidence[] }> {
  const candidates = files
    .filter(f => isCodeFile(f.path) && f.size > 80 && f.size < 220_000)
    .sort((a, b) => b.size - a.size)
    .slice(0, 8);

  const contents = await Promise.all(
    candidates.map(file => fetchFileContent(octokit, owner, repo, file.sha)),
  );

  const normalizedFiles = contents
    .filter((content): content is string => !!content)
    .map(normalizeCode)
    .filter(content => content.length >= 240);

  const snippets = extractSnippets(normalizedFiles);
  if (snippets.length === 0) {
    return { score: 0, evidence: [] };
  }

  const evidence: PlagiarismEvidence[] = [];

  for (const snippet of snippets) {
    const querySnippet = snippet.slice(0, 140).replace(/"/g, '');
    const q = `"${querySnippet}" in:file -repo:${owner}/${repo}`;

    try {
      const result = await octokit.search.code({ q, per_page: 10 });
      const uniqueRepos = Array.from(
        new Set(
          result.data.items
            .map(item => item.repository?.full_name)
            .filter((fullName): fullName is string => !!fullName),
        ),
      );

      evidence.push({
        snippet,
        matches: result.data.total_count,
        uniqueRepos,
      });
    } catch {
      evidence.push({
        snippet,
        matches: 0,
        uniqueRepos: [],
      });
    }
  }

  const totalMatches = evidence.reduce((sum, item) => sum + Math.min(item.matches, 20), 0);
  const uniqueRepoCount = new Set(evidence.flatMap(item => item.uniqueRepos)).size;
  const matchedSnippetCount = evidence.filter(item => item.matches > 0).length;

  const matchScore = Math.min(100, totalMatches * 1.8);
  const repoSpreadScore = Math.min(100, uniqueRepoCount * 12);
  const snippetConsistencyScore = (matchedSnippetCount / Math.max(snippets.length, 1)) * 100;

  const score = Math.round((matchScore * 0.5) + (repoSpreadScore * 0.25) + (snippetConsistencyScore * 0.25));

  return { score: Math.min(100, Math.max(0, score)), evidence };
}

export async function POST(req: Request) {
  try {
    const { url } = await req.json();
    const match = url.match(/github\.com\/([^\/]+)\/([^\/]+)/);
    if (!match) return NextResponse.json({ error: 'Invalid GitHub URL' }, { status: 400 });

    const owner = match[1];
    const repo = match[2].replace('.git', '');

    const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

    const [repoData, langs, commitsData, readme] = await Promise.all([
      octokit.repos.get({ owner, repo }),
      octokit.repos.listLanguages({ owner, repo }),
      octokit.repos.listCommits({ owner, repo, per_page: 10 }).catch(() => null),
      octokit.repos.getReadme({ owner, repo }).catch(() => null),
    ]);

    const defaultBranch = repoData.data.default_branch;
    const treeData = await octokit.git.getTree({ 
      owner, 
      repo, 
      tree_sha: defaultBranch, 
      recursive: 'true' 
    });

    const files = treeData.data.tree.filter(t => t.type === 'blob');
    const fileCount = files.length;
    const linesOfCode = fileCount * 120;
    const mainLanguage = Object.keys(langs.data)[0] || 'Unknown';

    const repoFiles: RepoFile[] = files
      .filter((f): f is { path: string; sha: string; size?: number } =>
        typeof f.path === 'string' && typeof f.sha === 'string',
      )
      .map(f => ({
        path: f.path,
        sha: f.sha,
        size: typeof f.size === 'number' ? f.size : 0,
      }));

    const plagiarismResult = await detectPlagiarism(octokit, owner, repo, repoFiles);
    const plagiarismScore = plagiarismResult.score;
    const passed = plagiarismScore < 35;

    const rawReadme = readme 
      ? Buffer.from(readme.data.content, 'base64').toString('utf-8')
      : '';
    
    // Summarise readme using Groq
    const readmeSummary = rawReadme ? await summariseReadme(rawReadme) : 'No README found.';

    return NextResponse.json({
      passed,
      repoUrl: url,
      plagiarismScore,
      metrics: {
        fileCount,
        linesOfCode,
        hasReadme: !!readme,
        mainLanguage,
        plagiarismSignals: {
          matchedSnippets: plagiarismResult.evidence.filter(e => e.matches > 0).length,
          uniqueMatchedRepos: new Set(plagiarismResult.evidence.flatMap(e => e.uniqueRepos)).size,
        },
      },
      tree: treeData.data.tree.slice(0, 50),
      commits: commitsData ? commitsData.data.map(c => ({ 
        sha: c.sha, 
        message: c.commit.message, 
        author: c.commit.author?.name 
      })) : [],
      readmeContent: readmeSummary,
      plagiarismEvidence: plagiarismResult.evidence.map(item => ({
        snippetPreview: item.snippet.slice(0, 100),
        matches: item.matches,
        uniqueRepos: item.uniqueRepos.slice(0, 5),
      })),
    });
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}