import { NextResponse } from 'next/server';
import { Octokit } from '@octokit/rest';
import { createGroq } from '@ai-sdk/groq';
import { generateText } from 'ai';

const groq = createGroq({
  apiKey: process.env.GROQ_API_KEY,
});

async function summariseReadme(readme: string): Promise<string> {
  try {
    const { text } = await generateText({
      model: groq('llama3-8b-8192'),
      prompt: `Summarise this README in 3-4 sentences, focusing on what the project does, tech stack, and key features:\n\n${readme.slice(0, 3000)}`,
    });
    return text;
  } catch {
    return readme.slice(0, 500); // fallback if summarisation fails
  }
}

const CODE_EXTENSIONS = new Set([
  'js', 'jsx', 'ts', 'tsx', 'py', 'java', 'c', 'cc', 'cpp', 'h', 'hpp',
  'cs', 'go', 'rs', 'kt', 'swift', 'php', 'rb', 'scala', 'sh', 'sql',
]);

const IGNORE_PATH_PARTS = [
  'node_modules/',
  'dist/',
  'build/',
  '.next/',
  '.git/',
  'vendor/',
  'coverage/',
  'target/',
  'out/',
  'bin/',
  'obj/',
];

const COMMON_BOILERPLATE_TOKENS = [
  'generated by',
  'next.config',
  'tailwind',
  'react.strictmode',
  'export default function',
  'createRoot',
  'from "react"',
  'from \"react\"',
  'import react',
  'use client',
];

type RepoFile = {
  path: string;
  sha: string;
  size?: number;
};

type PlagiarismEvidence = {
  snippet: string;
  sourcePath: string;
  extension: string;
  matches: number;
  uniqueRepos: string[];
};

function isCodeFile(path: string): boolean {
  const lower = path.toLowerCase();
  if (COMMON_BOILERPLATE_TOKENS.some(token => lower.includes(token))) return true;
  if (snippet.length < 40) return true;
  if (/^(import|export|from|class|interface|type|const|let|var)\s+/i.test(lower)) return true;
  return false;
  const ext = lower.split('.').pop();
  return !!ext && CODE_EXTENSIONS.has(ext);
function getFileExtension(path: string): string {
  const ext = path.toLowerCase().split('.').pop();
  return ext || '';
}

function extractSearchSnippets(path: string, content: string): Array<{ snippet: string; sourcePath: string; extension: string }> {
  const snippets: Array<{ snippet: string; sourcePath: string; extension: string }> = [];
  const extension = getFileExtension(path);
  const lines = content.split(/\r?\n/).map(line => line.trim()).filter(Boolean);

  for (const rawLine of lines) {
    const line = rawLine.replace(/\s+/g, ' ').trim();
    if (line.length < 45 || line.length > 160) continue;
    if (!/[a-zA-Z_]/.test(line)) continue;
    if (!/[(){}.=<>\[\]:]/.test(line)) continue;
    if (isLowSignalSnippet(line)) continue;

    const normalized = normalizeCode(line);
    if (normalized.length < 35) continue;
    if (snippets.some(existing => existing.snippet === normalized)) continue;

    snippets.push({
      snippet: normalized,
      sourcePath: path,
      extension,
    });

    if (snippets.length >= 4) break;
  }

  return snippets;
}

function rankCandidateFiles(files: RepoFile[]): RepoFile[] {
  const scored = files
    .filter(f => isCodeFile(f.path))
    .map(file => {
      const size = typeof file.size === 'number' ? file.size : -1;
      const sizePenalty = size > 220_000 ? -2 : 0;
      const hasKnownSize = size >= 0 ? 1 : 0;
      const usefulSize = size >= 80 || size === -1 ? 1 : -2;
      const depthBonus = file.path.split('/').length > 2 ? 0.5 : 0;
      const extBonus = ['ts', 'tsx', 'py', 'java', 'go', 'rs', 'cpp', 'cs'].includes(getFileExtension(file.path)) ? 1 : 0;
      const score = hasKnownSize + usefulSize + depthBonus + extBonus + sizePenalty;
      return { file, score };
    })
    .filter(item => item.score > 0)
    .sort((a, b) => b.score - a.score);

  return scored.slice(0, 12).map(item => item.file);
}

function extensionQuery(ext: string): string {
  return ext ? ` extension:${ext}` : '';
}

function computePlagiarismScore(evidence: PlagiarismEvidence[], snippetCount: number): number {
  const totalMatches = evidence.reduce((sum, item) => sum + Math.min(item.matches, 15), 0);
  const uniqueRepoCount = new Set(evidence.flatMap(item => item.uniqueRepos)).size;
  const matchedSnippetCount = evidence.filter(item => item.matches > 0).length;
  const strongHitCount = evidence.filter(item => item.matches >= 3).length;

  const matchVolumeScore = Math.min(100, totalMatches * 2.2);
  const repoDiversityScore = Math.min(100, uniqueRepoCount * 10);
  const consistencyScore = (matchedSnippetCount / Math.max(snippetCount, 1)) * 100;
  const strongHitScore = (strongHitCount / Math.max(snippetCount, 1)) * 100;

  const rawScore =
    (matchVolumeScore * 0.4) +
    (repoDiversityScore * 0.2) +
    (consistencyScore * 0.25) +
    (strongHitScore * 0.15);

  return Math.round(Math.min(100, Math.max(0, rawScore)));
}

function uniqueEvidence(evidence: PlagiarismEvidence[]): PlagiarismEvidence[] {
  const seen = new Set<string>();
  const deduped: PlagiarismEvidence[] = [];

  for (const item of evidence) {
    const key = `${item.sourcePath}::${item.snippet}`;
    if (seen.has(key)) continue;
    seen.add(key);
    deduped.push(item);
  }

  return deduped;
}

function sanitizeSearchSnippet(snippet: string): string {
  return snippet
    .replace(/["'`]/g, '')
    .replace(/\s+/g, ' ')
    .trim()
    .slice(0, 120);
}

function capSearchSnippetCount<T>(items: T[], maxCount: number): T[] {
  return items.slice(0, maxCount);
}

function hasLikelyCodeSignal(content: string): boolean {
  const normalized = normalizeCode(content);
  if (normalized.length < 120) return false;
  return /function|class|return|if\s*\(|for\s*\(|while\s*\(|=>/.test(normalized);
}

function collectSnippetCandidates(files: Array<{ path: string; content: string | null }>): Array<{ snippet: string; sourcePath: string; extension: string }> {
  const snippets: Array<{ snippet: string; sourcePath: string; extension: string }> = [];

  for (const file of files) {
    if (!file.content || !hasLikelyCodeSignal(file.content)) continue;
    snippets.push(...extractSearchSnippets(file.path, file.content));
    if (snippets.length >= 20) break;
  }

  return capSearchSnippetCount(snippets, 18);
}

async function detectPlagiarism(
  octokit: Octokit,
  owner: string,
  repo: string,
  files: RepoFile[],
): Promise<{ score: number; evidence: PlagiarismEvidence[] }> {
  const candidates = rankCandidateFiles(files);

  const filePayloads = await Promise.all(
    candidates.map(async (file) => ({
      path: file.path,
      content: await fetchFileContent(octokit, owner, repo, file.sha),
    })),
  );

  const snippets = collectSnippetCandidates(filePayloads);
  if (snippets.length === 0) {
    return { score: 0, evidence: [] };
  }

  const evidence: PlagiarismEvidence[] = [];

  for (const candidate of snippets) {
    const querySnippet = sanitizeSearchSnippet(candidate.snippet);
    if (querySnippet.length < 35) continue;

    const q = `"${querySnippet}" in:file -repo:${owner}/${repo}${extensionQuery(candidate.extension)}`;

    try {
      const result = await octokit.search.code({ q, per_page: 10 });
      const uniqueRepos = Array.from(
        new Set(
          result.data.items
            .map(item => item.repository?.full_name)
            .filter((fullName): fullName is string => !!fullName),
        ),
      );

      evidence.push({
        snippet: querySnippet,
        sourcePath: candidate.sourcePath,
        extension: candidate.extension,
        matches: result.data.total_count,
        uniqueRepos,
      });
    } catch {
      evidence.push({
        snippet: querySnippet,
        sourcePath: candidate.sourcePath,
        extension: candidate.extension,
        matches: 0,
        uniqueRepos: [],
      });
    }
  }

  const deduped = uniqueEvidence(evidence);
  const score = computePlagiarismScore(deduped, snippets.length);

  return { score, evidence: deduped };
}
  const contents = await Promise.all(
    candidates.map(file => fetchFileContent(octokit, owner, repo, file.sha)),
  );

  const normalizedFiles = contents
    .filter((content): content is string => !!content)
    .map(normalizeCode)
    .filter(content => content.length >= 240);

  const snippets = extractSnippets(normalizedFiles);
  if (snippets.length === 0) {
    return { score: 0, evidence: [] };
  }

  const evidence: PlagiarismEvidence[] = [];

  for (const snippet of snippets) {
    const querySnippet = snippet.slice(0, 140).replace(/"/g, '');
    const q = `"${querySnippet}" in:file -repo:${owner}/${repo}`;

    try {
      const result = await octokit.search.code({ q, per_page: 10 });
      const uniqueRepos = Array.from(
        new Set(
          result.data.items
            .map(item => item.repository?.full_name)
            .filter((fullName): fullName is string => !!fullName),
        ),
      );

      evidence.push({
        snippet,
        matches: result.data.total_count,
        uniqueRepos,
      });
    } catch {
      evidence.push({
        snippet,
        matches: 0,
        uniqueRepos: [],
      });
    }
  }

  const totalMatches = evidence.reduce((sum, item) => sum + Math.min(item.matches, 20), 0);
  const uniqueRepoCount = new Set(evidence.flatMap(item => item.uniqueRepos)).size;
  const matchedSnippetCount = evidence.filter(item => item.matches > 0).length;

  const matchScore = Math.min(100, totalMatches * 1.8);
  const repoSpreadScore = Math.min(100, uniqueRepoCount * 12);
  const snippetConsistencyScore = (matchedSnippetCount / Math.max(snippets.length, 1)) * 100;

  const score = Math.round((matchScore * 0.5) + (repoSpreadScore * 0.25) + (snippetConsistencyScore * 0.25));

  return { score: Math.min(100, Math.max(0, score)), evidence };
}

export async function POST(req: Request) {
  try {
    if (!process.env.GITHUB_TOKEN) {
      return NextResponse.json(
        { error: 'GitHub scanning is not configured. Add GITHUB_TOKEN to .env.local and restart the dev server.' },
        { status: 503 },
      );
    }

    if (!process.env.GROQ_API_KEY) {
      return NextResponse.json(
        { error: 'AI README summary is not configured. Add GROQ_API_KEY to .env.local and restart the dev server.' },
        { status: 503 },
      );
    }

    const { url } = await req.json();
    const match = url.match(/github\.com\/([^\/]+)\/([^\/]+)/);
    if (!match) return NextResponse.json({ error: 'Invalid GitHub URL' }, { status: 400 });

    const owner = match[1];
    const repo = match[2].replace('.git', '');

    const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

    const [repoData, langs, commitsData, readme] = await Promise.all([
      octokit.repos.get({ owner, repo }),
      octokit.repos.listLanguages({ owner, repo }),
      octokit.repos.listCommits({ owner, repo, per_page: 10 }).catch(() => null),
      octokit.repos.getReadme({ owner, repo }).catch(() => null),
    ]);

    const defaultBranch = repoData.data.default_branch;
    const treeData = await octokit.git.getTree({ 
      owner, 
      repo, 
      tree_sha: defaultBranch, 
      recursive: 'true' 
    });

    const files = treeData.data.tree.filter(t => t.type === 'blob');
    const fileCount = files.length;
    const linesOfCode = fileCount * 120;
    const mainLanguage = Object.keys(langs.data)[0] || 'Unknown';

    const repoFiles: RepoFile[] = files
      .filter((f): f is { path: string; sha: string; size?: number } =>
        typeof f.path === 'string' && typeof f.sha === 'string',
      )
      .map(f => ({
        path: f.path,
        sha: f.sha,
        size: typeof f.size === 'number' ? f.size : 0,
      }));

    const plagiarismResult = await detectPlagiarism(octokit, owner, repo, repoFiles);
    const plagiarismScore = plagiarismResult.score;
    const passed = plagiarismScore < 35;

    const rawReadme = readme 
      ? Buffer.from(readme.data.content, 'base64').toString('utf-8')
      : '';
    
    // Summarise readme using Groq
    const readmeSummary = rawReadme ? await summariseReadme(rawReadme) : 'No README found.';

    return NextResponse.json({
      passed,
      repoUrl: url,
      plagiarismScore,
      metrics: {
        fileCount,
        linesOfCode,
        hasReadme: !!readme,
        mainLanguage,
        plagiarismSignals: {
          matchedSnippets: plagiarismResult.evidence.filter(e => e.matches > 0).length,
          uniqueMatchedRepos: new Set(plagiarismResult.evidence.flatMap(e => e.uniqueRepos)).size,
        },
      },
      tree: treeData.data.tree.slice(0, 50),
      commits: commitsData ? commitsData.data.map(c => ({ 
        sha: c.sha, 
        message: c.commit.message, 
        author: c.commit.author?.name 
      })) : [],
      readmeContent: readmeSummary,
      plagiarismEvidence: plagiarismResult.evidence.map(item => ({
        snippetPreview: item.snippet.slice(0, 100),
        sourcePath: item.sourcePath,
        matches: item.matches,
        uniqueRepos: item.uniqueRepos.slice(0, 5),
      })),
    });
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}